inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'bin/**/*'

Style/GuardClause:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 23

Metrics/PerceivedComplexity:
  Max: 23
